# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 08:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20170829_1641'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ('username',)},
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Author'),
        ),
    ]
